language: csharp
solution: RsaHelper.sln

include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
      script:
        - cd RsaHelper
        - dotnet restore
        - dotnet build -c Release